name: CI-Release

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - refactor
    
jobs:
  build-binary:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: build binary
      run: |
        docker build . -t builder
        docker run --rm -v ${PWD}:/project builder make
    - uses: actions/upload-artifact@master
      with:
       name: binary
       path: "*.rpx"
  deploy-binary:
    needs: build-binary
    runs-on: ubuntu-18.04
    steps:   
    - name: Get environment variables
      id: get_repository_name
      run: |
        echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
        echo DATETIME=$(echo $(date '+%Y%m%d-%H%M%S')) >> $GITHUB_ENV
    - uses: actions/download-artifact@master
      with:
        name: binary
        path: wiiu/apps/SaveMiiModWUTPort
    - name: zip artifact
      run: zip -r ${{ env.REPOSITORY_NAME }}_${{ env.DATETIME }}.zip wiiu
